### ISSUE TITLE
Underscores are replaced with hyphens in header names

### ISSUE THREAD

**Issue by cosjak** [pintsized/lua-resty-http#106]
```
connection:request_uri("....", {
    method = "POST",
    body = "....",
    headers = {
      sso_token = "...."
    }
})
```

This code results in this request header
>  "sso-token: ...."

because http_headers.lua forces hyphened header name to be stored:
`rawset(t, k_hyphened, v)`
 
Expected result: underscore is a legal symbol in HTTP header name in accordance with HTTP specification and must not be transformed into hyphens.

**Comment by pintsized** [comment]
Hmm, yes, you're correct technically speaking. Practically speaking, both Nginx and Apache require non-default configuration to handle header field names with underscores in them (e.g. `underscores_in_headers` for Nginx defaults to `Off`), and the default OpenResty behaviour is to normalise these so that underscores / hyphens can be treated equally in Lua tables: https://github.com/openresty/lua-nginx-module#ngxreqget_headers

So if we're to make a change here, it should be along the lines of non-default "raw" mode, which was also added to the lua-nginx-module functions at some point. I'm actually thinking of refactoring the headers stuff out into a separate headers module (with field value token parsing etc), so I'm reluctant to just throw a quick (potentially breaking) fix in for this.

Can I suggest you use hyphens for your custom header field names? It really is very unusual to opt for underscores.

If you can't adjust or translate the header names that your backend is expecting, perhaps it's best for now to fork this repo, and comment out this line: https://github.com/pintsized/lua-resty-http/blob/master/lib/resty/http.lua#L606

Be sure to test the behaviour, but it should essentially give you the "raw" headers mode you're looking for. You'll need to make sure your headers table is exactly how you want it (taking case insensitivity into consideration for example).

**Comment by cosjak** [comment]
Yes, I am aware of this old underscored headers war (Apache2, Nginx.. and even IIS :D). 

But current module's behavior makes no sense, IMHO. When I put some header into request this means that someone expects this particular header on the other side of the connection. There is no reason to replace '_' with '-' because it does no any good but breaks the things. It would be better to raise an error to make it clear. Or to have it configurable.

To my regret I have to communicate with some third party SSO server and it expects 'sso_token' header - I cannot change this.

The fastest work-around for me was to go to this SSO server via the same Nginx instance while restoring header during proxying.
```
  server {
    listen 9080;

    location / {
      proxy_set_header sso_token $http_sso_token;

      set $sso_server ${SSO_SERVER_URL};
      proxy_pass $sso_server;
    }
  }
```

UGH!  :D
