### ISSUE TITLE
Limit on GET request length 

### ISSUE THREAD

**Issue by ovoshlook** [pintsized/lua-resty-http#116]
Hi. I found strange behaivor
One of my services expecting very big request (over 600kb) 
It is a GET request and URI really big.

I found that when i make this request httpClient sends me error 
recv() failed (104: Connection reset by peer)
If i decrase request length - request runs succesfully.

Is there any chance to fix this limit if it exists?

**Comment by pintsized** [comment]
There's no limit imposed in this library, but this doesn't look like strange behaviour either. The error indicates the server reset the connection, most likely because it took too long to transfer the request, which with a 600KB GET is not really strange. I'm assuming you've set a long send timeout with `set_timeouts()`?

And you're sure your service is expecting such a large request line? Default Nginx config would give up and return status 414 with a request line above 8KB I think. A 600KB GET request is frankly enormous. This is what POST / PUT are for. However, theoretically it should be possible if the server is built to handle it. Just seems like a really bad idea ;)

**Comment by ovoshlook** [comment]
Yep. I agree About Bad idea. It will be refactored on client side. Just legacy staff that will be removed in feture commits.
Regarding timeounts yep. I already set it to 5 seconds and for most cases it works good.
Regarding service - yes it can because without proxy (openresty) it works good directly.
Also i temporary set.
 client_body_buffer_size     10M;
 client_max_body_size        10M;

in nginx.conf
It helped me to resolve some issues when request comes to openresty,
thants why i asked about httpClient side because on intput it works well.
