### ISSUE TITLE
port redirect error

### ISSUE THREAD

**Issue by huangjingkai** [pintsized/lua-resty-http#27]
when app response 302 redirect, client got port 8080(HTTP header: Location) then it turn to request error. How can i change to port 80 ?

client --> nginx(port: 80) --> app(port:8080).

Thanks for your reply.

**Comment by pintsized** [comment]
Hi,

If you're connected on port 80, and receive a `302` with a `Location` header directing you to port 8080, you'll need to create a new connection on port 8080. Underneath it all, it's just a TCP/IP connection - if the port has changed then you are connected to the wrong thing.

Are you using the `proxy_response` / `proxy_request` functions? You'll need to do things manually if so. They are just convenience methods for simple cases.

If you need any further help, please post a minimal gist example so that I can see what you're trying to do in more detail.
