### ISSUE TITLE
proxy_response cant forward the app heartbeat packet to client

### ISSUE THREAD

**Issue by guanglinlv** [pintsized/lua-resty-http#28]
hi,
I find `proxy_response` cant send the app heartbeat packet(only 6 bytes) to client immediately because using `ngx.print`. so i have to invoke `ngx.flush` after print. may i have your some good advice?
see http://wiki.nginx.org/HttpLuaModule#ngx.flush

**Comment by pintsized** [comment]
Hi. Well `proxy_response` is really just a convenience function, requested by users. If you need greater control, then it's quite trivial to implement your own version, and decide to call `ngx.flush` when you wish. If your app has a 6 byte heartbeat then you can test for that in your code, and decide to flush this immediately. Sounds like you're doing this already?

**Comment by guanglinlv** [comment]
yes,i had to invoked `ngx.flush for my streaming output, but I'm not sure that  delaying send is decided by `ngx.print or nginx, how to config it ?

**Comment by pintsized** [comment]
It might be best to ask on the OpenResty mailing list, since others may have more experience with this than me. But my understanding is that `ngx.print` will push data to the Nginx output chain and it's up to Nginx to buffer however it wants. If however you call `ngx.flush` in synchronous mode after `ngx.print`, then the print effectively becomes synchronous (though remaining non-blocking to the Nginx event loop), and the data is sent to the system send buffer more directly.

```lua
ngx.print(chunk)
ngx.flush(true)
```

Beyond this, it is up to Nginx to get those bytes out on the wire, and I'm not sure if there's any more control available for this.

https://github.com/openresty/lua-nginx-module#ngxflush
https://github.com/openresty/lua-nginx-module#ngxprint

**Comment by guanglinlv** [comment]
ok, thanks for your patiently replay.
