### ISSUE TITLE
cannt work at init_worker_by_lua_file 

### ISSUE THREAD

**Issue by imiskolee** [pintsized/lua-resty-http#52]
the nginx debug info:
`init_worker_by_lua_file error: ...lua/traffic-monitoring/lua-resty-http/lib/resty/http.lua:90: API disabled in the context of init_worker_by_lua*
stack traceback:
	[C]: in function 'ngx_socket_tcp'
	...lua/traffic-monitoring/lua-resty-http/lib/resty/http.lua:90: in function 'new'
	/usr/local/nginx/conf/lua/traffic-monitoring/report.lua:4: in main chunk
2016/03/31 19:12:38 [error] 10#0: init_worker_by_lua_file error: ...lua/traffic-monitoring/lua-resty-http/lib/resty/http.lua:90: API disabled in the context of init_worker_by_lua*`

**Comment by pintsized** [comment]
You need to familiarise yourself with the ngx_lua module more thoroughly. Please review the documentation: https://github.com/openresty/lua-nginx-module

Specifically, note that `ngx.socket.tcp` is not available at the `init` or `init_worker` phases, and the solution you are probably looking for is to use `ngx.timer.at` to start a light thread during the `init_worker`. This child thread will have the ability to create tcp sockets. Examples: https://github.com/openresty/lua-nginx-module#ngxtimerat

In general, if you're unsure about something to do with OpenResty, I'd encourage you to ask on the mailing list rather than file a but report against a specific module.
