### ISSUE TITLE
the "request" method should encode url?

### ISSUE THREAD

**Issue by bradelement** [pintsized/lua-resty-http#59]
for example:

res, err = httpc:request(params)
params.path = "/aaa/bbb===bbb/cccc"

i think the lib itself should encode this path inside the function.
we have a scene that we need to get a restful url like /info/:id/start,
id is base64_encoded, so it sometimes involve '=' and the lib fail to connect.

**Comment by pintsized** [comment]
Hi, sorry for the slow reply.

It's not really possible to do this at the library level. That is, we can't simply encode the URL as an entire thing, one needs knowledge about the different components and to decide what must be encoded, and what mustn't be. Otherwise we'll end up doubly-encoding some things, or encoding legitimate URI characters.

In your case, you should encode your ID correctly before adding it to the path, since you know it will have characters that must be encoded.

**Comment by bradelement** [comment]
makes sense. thank you for your reply.
