### ISSUE TITLE
connect to nginx UnixSocket -> Invalid Host Header (@Server)

### ISSUE THREAD

**Issue by JakSprats** [pintsized/lua-resty-http#60]
I am using lua-resty-http to connect to a Nginx Unix Socket and send a POST request
The Host header causes a http header parse error in Nginx

LOG: http.lua:551: send_request():
  POST /__agent HTTP/1.1^M
  Content-Length: 181^M
  Content-Type: application/x-www-form-urlencoded^M
  User-Agent: lua-resty-http/0.06 (Lua) ngx_lua/10001^M
  Host: unix:/tmp/sticky_nginx_socket_12878^M

NGINX_LOG:
2016/05/19 13:27:55 [info] 12878#0: *5 client sent invalid host header while reading client request headers, client: unix:, server: , request: "POST /__agent HTTP/1.1", host: "unix:/tmp/sticky_nginx_socket_12878"

I hacked a solution by replacing file http.lua function:_M.send_request() line 532
    headers["Host"] = self.host
with:
    if (string.sub(self.host,1,5) == "unix:") then
        headers["Host"] = "127.0.0.1";
     else
        headers["Host"] = self.host;
    end

It's not the prettiest solution, but it works.

**Comment by pintsized** [comment]
In this case you'll need to manually set your Host header. The invalid Host header is only generated as a guess because you haven't set one, and in the case of a unix domain socket that's a bit of a weird case.

I've just pushed a change to master which provides a useful error message instead of just failing.
