### ISSUE TITLE
res:read_body() error: can't resume a dead coroutine

### ISSUE THREAD

**Issue by mango009** [pintsized/lua-resty-http#74]
I'm trying to use the library to make a post request to HTTPS URL. 

local res, err = httpc:request_uri(......)

if res then
  local body, err = res:read_body()
  if err then
      ngx.log(ngx.STDERR, 'failed tp read body:", err)  -- error: can't resume a dead coroutine
  end
end

What could be the problem here?

**Comment by pintsized** [comment]
Hi,

Looks like you're mixing up the two APIs. If you use the simple `request_uri` interface then everything it taken care of for you, and the body will already be read into `res.body`. The error you're getting is because you're trying to start the body reader coroutine after it has already finished.

`read_body()` is for use with the "generic" interface, where you handle the connection manually. With the generic interface you can stream the body too (instead of allocating the whole thing to memory in one go) so it's much more flexible.

**Comment by mango009** [comment]
Thanks so much. That works!
One more question, is there anyway that I can print/ngx.log the request (header+body)? I need to inspect these because I'm doing a HTTPS and cannot get it from wireshark.

Thanks again for the great utility!

**Comment by pintsized** [comment]
If you raise the Nginx log level to DEBUG, you'll see the request line and headers in the log. It doesn't log the body however.
