### ISSUE TITLE
Return part of range request

### ISSUE THREAD

**Issue by skycrew** [pintsized/lua-resty-http#92]
Hi,

Would it be possible to return part of range request?

For example:
I make a GET request with range header bytes=0-150 but I only want to print bytes from 50-100.

possible?

**Comment by pintsized** [comment]
Of course - you can just use `string.sub` on your response body. Remember that the first byte in a range request is `0`, so you'll want to do something like `string.sub(body, start + 1, end + 1)`.

If you're using the body reader (streaming) then it might be a little more complex, since the data you wish to print may span one or more chunks as they arrive via the body reader. Here is an example of a coroutine "filter" which in turn calls the body reader, and only yields the data specified in a range request: https://github.com/pintsized/ledge/blob/master/lib/ledge/ledge.lua#L3163

**Comment by skycrew** [comment]
thanks for your tips
