### ISSUE TITLE
Sending two requests

### ISSUE THREAD

**Issue by snyff** [pintsized/lua-resty-http#98]
Hi,
I'm trying to send two requests once a request hits Nginx. My current configuration looks like: 

```
        location / {
          content_by_lua '
              local http = require "resty.http"
              local httpc = http.new()
              local res, err = httpc:request_uri("https://analytics/", {
              method = "POST",
                body = "a=1&b=2",
                  headers = {
                  ["Content-Type"] = "application/x-www-form-urlencoded",
        }
      })
      if err then
        ngx.log(ngx.ERR, err)
      end
            httpc:connect("backend", 1234)
            httpc:proxy_response(httpc:proxy_request())
            httpc:set_keepalive()
      ';
        }
```

It works but it's incredibly slow. Is there a better way to do this?

**Comment by pintsized** [comment]
Hi. Firstly I wouldn't recommend trying to reuse the connection like that. If you want to make two requests, then do `httpc.new()` for each one. It's not expensive to do this, and correct behaviour isn't guaranteed if you don't.

I don't think that's related to your speed issue however, but I'd definitely start by getting that right.

If things are still slow, check the error log (raising the Nginx log level to `debug` will give you a bit more info about the http request), and check your backend is actually responding as you expect. Perhaps things are timing out? Perhaps you have resolution issues to "backend" for example?

Also consider separating `proxy_request` out, so you can check the return value instead of blindly passing it into `proxy_response`.

**Comment by snyff** [comment]
I tried with two http.new() and it doesn't seem to work. Thanks for the answer though

**Comment by pintsized** [comment]
14615e96c79d01bd2785022986ccf51cbfc1a7f9 Added a test to confirm reusing the instance in this way is indeed safe. Your problem must be elsewhere.
